framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

    error_controller: App\Controller\ErrorController::show

    cache:
        app: cache.adapter.filesystem

        system: cache.adapter.system

    serializer:
        enabled: true
        enable_attributes: true
        mapping:
            paths: ['%kernel.project_dir%/src/Entity']

    validation:
        enabled: true
        enable_attributes: true
        mapping:
            paths: ['%kernel.project_dir%/src/Entity']

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
