# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    # Error handling
    error_controller: App\Controller\ErrorController::show

    # Cache configuration
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options: cache.adapter.redis, cache.adapter.memcached, cache.adapter.pdo, cache.adapter.system, cache.adapter.filesystem
        app: cache.adapter.filesystem

        # The "system" cache is used internally by Symfony components.
        # Other options: cache.adapter.redis, cache.adapter.memcached, cache.adapter.pdo, cache.adapter.apcu, cache.adapter.system, cache.adapter.filesystem
        system: cache.adapter.system

    # Serializer configuration
    serializer:
        enabled: true
        enable_attributes: true
        mapping:
            paths: ['%kernel.project_dir%/src/Entity']

    # Validator configuration
    validation:
        enabled: true
        enable_attributes: true
        mapping:
            paths: ['%kernel.project_dir%/src/Entity']

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
