nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Accept', 'Authorization', 'Content-Type', 'X-API-KEY', 'X-Requested-With']
        expose_headers: ['X-RateLimit-Remaining', 'X-RateLimit-Retry-After', 'X-RateLimit-Limit']
        allow_credentials: true
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: ['Accept', 'Authorization', 'Content-Type', 'X-API-KEY', 'X-Requested-With']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            allow_credentials: true
            max_age: 3600 