nelmio_api_doc:
    documentation:
        info:
            title: Restaurant API
            description: API RESTful para gestión de restaurantes - Prueba técnica backend
            version: 1.0.0
            contact:
                name: API Support
                email: support@restaurantapi.local
        servers:
            - url: http://localhost:8080
              description: Servidor de desarrollo
        components:
            securitySchemes:
                ApiKeyAuth:
                    type: apiKey
                    in: header
                    name: X-API-KEY
                    description: API Key para autenticación
                BearerAuth:
                    type: http
                    scheme: bearer
                    description: Token Bearer en header Authorization
            schemas:
                Error:
                    type: object
                    properties:
                        error:
                            type: boolean
                            example: true
                        code:
                            type: integer
                            example: 400
                        message:
                            type: string
                            example: "Bad Request"
                        details:
                            type: string
                            example: "Descripción detallada del error"
                        timestamp:
                            type: string
                            format: date-time
                            example: "2024-01-15 10:30:45"
        security:
            - ApiKeyAuth: []
            - BearerAuth: []
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$)
            host_patterns: []
            with_attribute: true
    models:
        names:
            - { alias: Restaurant, type: App\Entity\Restaurant, groups: [restaurant:read] }
            - { alias: User, type: App\Entity\User, groups: [user:read] } 