framework:
    rate_limiter:
        # Rate limiting general por IP
        api_general:
            policy: 'sliding_window'
            limit: 100
            interval: '1 hour'
            
        # Rate limiting para operaciones de escritura (POST, PUT, DELETE)
        api_write_operations:
            policy: 'sliding_window'
            limit: 30
            interval: '10 minutes'
            
        # Rate limiting para login por IP
        login_ip:
            policy: 'sliding_window'
            limit: 10
            interval: '15 minutes'
            
        # Rate limiting para usuarios autenticados (más permisivo)
        authenticated_user:
            policy: 'sliding_window'
            limit: 200
            interval: '1 hour'
            
        # Rate limiting estricto para usuarios no autenticados
        anonymous_user:
            policy: 'sliding_window'
            limit: 50
            interval: '1 hour'
            
        # Rate limiting para creación de usuarios
        user_registration:
            policy: 'sliding_window'
            limit: 5
            interval: '1 hour' 