controllers:
    resource:
        path: ../src/
        namespace: App
    type: attribute
    exclude: 
        - '../src/Entity/'
        - '../src/DependencyInjection/'
        - '../src/Kernel.php'
        - '../src/DataFixtures/'
        - '../src/RateLimiting/'
        - '../src/Security/'
