parameters:

services:
    _defaults:
        autowire: true      
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    
    # Rate Limiter Services
    App\RateLimiting\EventListener\RateLimitListener:
        arguments:
            $apiGeneralLimiter: '@limiter.api_general'
            $apiWriteOperationsLimiter: '@limiter.api_write_operations'
            $loginIpLimiter: '@limiter.login_ip'
            $authenticatedUserLimiter: '@limiter.authenticated_user'
            $anonymousUserLimiter: '@limiter.anonymous_user'
            $userRegistrationLimiter: '@limiter.user_registration'

    # Repository Aliases
    App\Repository\UserRepository: '@App\Users\Repository\UserRepository'
    App\Repository\RestaurantRepository: '@App\Restaurants\Repository\RestaurantRepository'
    
    # Controller Aliases
    App\Controller\AuthController: '@App\Users\Controller\AuthController'
    App\Controller\RestaurantSearchController: '@App\Restaurants\Controller\RestaurantSearchController'
    
    # EventListener Aliases
    App\EventListener\RateLimitListener: '@App\RateLimiting\EventListener\RateLimitListener'
    App\EventListener\RateLimitResponseListener: '@App\RateLimiting\EventListener\RateLimitResponseListener'
