# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event listeners, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    # Rate Limiter Services
    App\RateLimiting\EventListener\RateLimitListener:
        arguments:
            $apiGeneralLimiter: '@limiter.api_general'
            $apiWriteOperationsLimiter: '@limiter.api_write_operations'
            $loginIpLimiter: '@limiter.login_ip'
            $authenticatedUserLimiter: '@limiter.authenticated_user'
            $anonymousUserLimiter: '@limiter.anonymous_user'
            $userRegistrationLimiter: '@limiter.user_registration'

    # Repository Aliases
    App\Repository\UserRepository: '@App\Users\Repository\UserRepository'
    App\Repository\RestaurantRepository: '@App\Restaurants\Repository\RestaurantRepository'
    
    # Controller Aliases
    App\Controller\AuthController: '@App\Users\Controller\AuthController'
    App\Controller\RestaurantSearchController: '@App\Restaurants\Controller\RestaurantSearchController'
    
    # EventListener Aliases
    App\EventListener\RateLimitListener: '@App\RateLimiting\EventListener\RateLimitListener'
    App\EventListener\RateLimitResponseListener: '@App\RateLimiting\EventListener\RateLimitResponseListener'
